In [1]:
import pandas as pd

In [5]:
# df_producto_yerba = pd.read_csv("data/yerba.csv")
df_prod = pd.read_csv("../data/producto_yerba.csv")

In [26]:
# df_productos.marca.value_counts()

In [27]:
# df_productos

In [17]:
import re

def limpieza_nombre(x):

    con_palo = False
    sin_palo = False
    tacc = False
    
    if 'con palo' in x:
        con_palo = True
    if 'sin palo' in x:
        sin_palo = True
    if 'tacc' in x:
        tacc = True
    
    peso = re.search(r'\d.*', x)
    print(peso.group())
    
            
    return [peso, tacc, con_palo, sin_palo]
    
df_prod[['peso', 'tacc', 'con_palo', 'sin_palo']] = df_prod.nombre.apply(lambda x: limpieza_nombre(x.lower()))

## de momento trabajamos con 500gr y 1kg
## se puede hacer por mas tipos de peso
# df_prod['peso'] = df_prod['nombre'].apply(lambda x: '500 Gr' if '500 Gr' in x else ('1 Kg' if '1 Kg' in x else 'otro'))

4flex taragui 500 gr
500 gr
4 flex sin palo taragui 500 gr
500 gr
4flex suave union 500 gr
25 un
4flex taragui 1 kg
4 flex mañanita 1 kg
1950 amanda 1 kg
4 flex mañanita 500 gr
500 gr - nv
250 gr
500 gr sin tacc - nvo
1 kg
500 gr
1950 amanda 500 gr
500 gr
1 kg
1 kg
500 gr
500 gr
4flex taragui 1 kg
500 gr
4 flex union 250 gr
500 gr
500 gr
500 gr
500 gr
50 un
500 gr
500 gr
1 kg
500 gr
4 flex taragui 250 gr
500 gr
500 gr
1 kg
1 kg sin tacc - nvo
1 kg sin ta
500 gr
500 gr
1 kg
1pqx1k
500 gr
500 gr
500 gr
1 kg
500 gr
4flex taragui 500 gr
500 gr
4 flex sin palo taragui 500 gr
500 gr
4flex suave union 500 gr
25 un
4flex taragui 1 kg
4 flex mañanita 1 kg
1950 amanda 1 kg
4 flex mañanita 500 gr
500 gr - nv
250 gr
500 gr sin tacc - nvo
1 kg
500 gr
1950 amanda 500 gr
500 gr
1 kg
1 kg
500 gr
500 gr
4flex taragui 1 kg
500 gr
4 flex union 250 gr
500 gr
500 gr
500 gr
500 gr
50 un
500 gr

ValueError: Columns must be same length as key

In [29]:
df_prod[df_prod.peso == 'otro']

,cantSucursalesDisponible,id,marca,nombre,precioMax,precioMin,precio_bulto_max_con_iva,precio_bulto_max_sin_iva,precio_bulto_min_con_iva,precio_bulto_min_sin_iva,precio_unitario_bulto_max_con_iva,precio_unitario_bulto_max_sin_iva,precio_unitario_bulto_min_con_iva,precio_unitario_bulto_min_sin_iva,presentacion,peso
5,14,7790387800050,TARAGUÍ,Yerba Mate en Saquitos Taragui 25 Un,126.5,118.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.0 un,otro
11,12,7791720026335,CARREFOUR,Yerba Mate con Palo Sin TACC Carrefour 250 Gr,162.0,162.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,250.0 gr,otro
23,9,7790387014631,UNIÓN,Yerba Mate Suave 4 Flex Union 250 Gr,240.5,240.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,250.0 gr,otro
28,9,7790387800067,TARAGUÍ,Yerba Mate en Saquitos Taragui 50 Un,310.0,310.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0 un,otro
33,6,7790387013634,TARAGUÍ,Yerba Mate con Palo 4 Flex Taragui 250 Gr,240.5,240.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,250.0 gr,otro
42,3,7790070509055,Sin marca,Yerba Cruz Malta Eco 1pqx1k,883.0,883.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None none,otro
53,14,7790387800050,TARAGUÍ,Yerba Mate en Saquitos Taragui 25 Un,126.5,118.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.0 un,otro
59,12,7791720026335,CARREFOUR,Yerba Mate con Palo Sin TACC Carrefour 250 Gr,162.0,162.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,250.0 gr,otro
71,9,7790387014631,UNIÓN,Yerba Mate Suave 4 Flex Union 250 Gr,240.5,240.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,250.0 gr,otro
76,9,7790387800067,TARAGUÍ,Yerba Mate en Saquitos Taragui 50 Un,310.0,310.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0 un,otro